- task: DotNetCoreCLI@2
  inputs:
    command: 'run'
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: 
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'